"""Optional Python. Delete this file if you don't need custom logic.

def on_load(game): ...
def on_turn(game): ...
def on_enter(game, location_id): ...
def on_leave(game, location_id): ...
def on_use_item(game, item_id, target) -> bool: ...
def on_talk(game, npc_id) -> bool: ...
def on_combat_start(game, encounter_id): ...
def on_combat_end(game, encounter_id, won: bool): ...
def on_command(game, verb, args) -> bool: ...
def on_ending(game, kind): ...

Returning True from on_command / on_use_item / on_talk means you handled it.
"""
